set(CPACK_PACKAGE_NAME "${TARGET_NAME}")
set(CPACK_PACKAGE_DIRECTORY "packages")
set(CPACK_PACKAGE_VENDOR "Nickolay Muraviev")
set(CPACK_PACKAGE_VERSION_MAJOR ${CMAKE_PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${CMAKE_PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${CMAKE_PROJECT_VERSION_PATCH})
set(CPACK_WIX_UPGRADE_GUID 193923F9-F4F0-4F30-B2CA-6C97C2D3FA45)
set(CPACK_CREATE_DESKTOP_LINKS "GPNE")
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GPNE")
set(CPACK_PACKAGE_EXECUTABLES ${TARGET_NAME} "GPNE")
# FIXME: error with file extension
set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/LICENSE)

set(CPACK_COMPONENTS_ALL Unspecified)

if(WIN32)
    set(CPACK_GENERATOR WIX)
    set(CPACK_WIX_VERSION 4)
elseif(APPLE)
    set(CPACK_GENERATOR ZIP)
endif ()

include(CPack)