[package]
name = "ptn" # the name of the package
version = "0.1.0"    # the current version, obeying semver
edition = "2021"

[dependencies]
nalgebra = "0.32.1"
libc = "0.2.112"
rand = "0.8.4"
chrono = "0.4.19"
indexmap = { version = "1.8.0", features = ["std"] }
num-traits = "0.2.15"
num = "0.4.3"
rayon = "1.7.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
thiserror = "1.0.63"
good_lp = { version = "1.12.0", features = ["microlp"], default-features = false }

[[bench]]
name = "cycle_lookup_bench"
#path = "benches/cycle_lookup_bench.rs"
harness = false

[dev-dependencies]
criterion = "0.5.1"